---
title: "Water Market Models"
author: "Kelp"
date: "4/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(broom)

```

```{r}
water <- read_csv(here("HW2_Water.csv")) %>% 
  clean_names() %>% 
  mutate(TMAC = mc_agriculture +
           mc_meat+
           mc_industrial)

```

```{r}
lm_tmac <- tidy(lm(TMAC ~ reduced_water_use_abatement, water))


```


```{r}
agri <- lm(mc_agriculture ~ reduced_water_use_abatement, water)

agri <- tidy(agri)

meat <- tidy(lm(mc_meat ~ reduced_water_use_abatement, 
     water))

ind <- tidy(lm(mc_industrial ~ reduced_water_use_abatement, 
     water))

urban <- tidy(lm(mc_urban ~ reduced_water_use_abatement, 
     water))

```


```{r}
ggplot(water) +
  geom_smooth(method = lm, 
              aes(x = reduced_water_use_abatement,
                  y = mc_agriculture),
              se = FALSE,
              color = "darkgreen",) +
  geom_text(label = "Ag",
            x = 155,
            y = 85,
            color = "darkgreen")+
  geom_smooth(method = lm, 
              aes(x = reduced_water_use_abatement,
                  y = mc_meat),
              se = FALSE,
              color = "darkred") +
   geom_text(label = "M",
            x = 155,
            y = 65,
            color = "darkred")+
  geom_smooth(method = lm, 
              aes(x = reduced_water_use_abatement,
                  y = mc_industrial),
              se = FALSE,
              color = "black")+
     geom_text(label = "I",
            x = 155,
            y = 125,
            color = "black")+
  geom_smooth(method = lm, 
              aes(x = reduced_water_use_abatement,
                  y = mc_urban),
              se = FALSE,
              color = "blueviolet")+
  geom_text(label = "U",
            x = 155,
            y = 75,
            color = "blueviolet")+
  theme_minimal() +
  labs(x = "Q (AF)",
       y = "P ($/AF)")+
  ylim(0,150)
  
```

```{r}
## Graph demand curves
demand <- tribble(~"water_use", ~"ag", ~"meat", ~"industrial", ~"urban",
                  0, 88.636, 84.481, 233.093, 165.271,
                  150, 12.136, 28.231, 63.593, 75.721)

ggplot(demand) +
  geom_smooth(method = lm, 
              aes(x = water_use,
                  y = ag),
              se = FALSE,
              color = "darkgreen")+
  geom_text(label = "Ag",
            x = 153,
            y = 13,
            color = "darkgreen")+
  geom_smooth(method = lm, 
              aes(x = water_use,
                  y = meat),
              se = FALSE,
              color = "darkred") +
     geom_text(label = "M",
            x = 153,
            y = 27,
            color = "darkred")+
  geom_smooth(method = lm, 
              aes(x = water_use,
                  y = industrial),
              se = FALSE,
              color = "black")+
       geom_text(label = "I",
            x = 153,
            y = 63,
            color = "black")+
  geom_smooth(method = lm, 
              aes(x = water_use,
                  y = urban),
              se = FALSE,
              color = "blueviolet")+
    geom_text(label = "U",
            x = 153,
            y = 75,
            color = "blueviolet")+
    theme_minimal()+
  labs(x = "Q (AF)",
       y = "P ($/AF)")
```

